stages:
  - build
  - test

variables:
  PLAYWRIGHT_BROWSERS_PATH: "/usr/local/playwright-browsers"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1" # Skip the automatic browser download

before_script:
  - apt-get update -qq && apt-get install -y -qq curl unzip wget
  - wget https://github.com/microsoft/playwright-cli/releases/download/v1.13.0/playwright-cli-linux -O /usr/local/bin/playwright
  - chmod +x /usr/local/bin/playwright
  - npm install -D @playwright/test
  - npx playwright install --browsers-path $PLAYWRIGHT_BROWSERS_PATH

cache:
  paths:
    - .nuget/packages/
    - node_modules/
    - $PLAYWRIGHT_BROWSERS_PATH

build_job:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

test_job:
  stage: test
  script:
    - dotnet test --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
  artifacts:
    when: always
    paths:
      - TestResults.trx
    reports:
      junit: TestResults.trx
